// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTrivia.Data;

#nullable disable

namespace MyTrivia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528115826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MyTrivia.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyTrivia.Models.Trivia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuizQuestion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriviaBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriviaTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("Trivias");
                });

            modelBuilder.Entity("MyTrivia.Models.TriviaTag", b =>
                {
                    b.Property<int>("TriviaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TriviaId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TriviaTags");
                });

            modelBuilder.Entity("MyTrivia.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoUrl")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MyTrivia.Models.Trivia", b =>
                {
                    b.HasOne("MyTrivia.Models.Video", "Video")
                        .WithMany("Trivias")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Video");
                });

            modelBuilder.Entity("MyTrivia.Models.TriviaTag", b =>
                {
                    b.HasOne("MyTrivia.Models.Tag", "Tag")
                        .WithMany("TriviaTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTrivia.Models.Trivia", "Trivia")
                        .WithMany("TriviaTags")
                        .HasForeignKey("TriviaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Trivia");
                });

            modelBuilder.Entity("MyTrivia.Models.Tag", b =>
                {
                    b.Navigation("TriviaTags");
                });

            modelBuilder.Entity("MyTrivia.Models.Trivia", b =>
                {
                    b.Navigation("TriviaTags");
                });

            modelBuilder.Entity("MyTrivia.Models.Video", b =>
                {
                    b.Navigation("Trivias");
                });
#pragma warning restore 612, 618
        }
    }
}
